
data <- read.csv(file="D:/INAA.csv", header=TRUE, sep=",")
data
class(data)
View(data)
write.csv(data, file="data2.csv", quote=TRUE, na="na", row.names=FALSE)
install.packages("xlsx")
require("xlsx")
mydata <- read.xlsx(file="D:/FS 2020-21/Sample Slip/20.02.21.xlsx", 1)
View(mydata)
help(read.xlsx)
class(mydata)
length(mydata)
length(data)
write.xlsx(data, file="data2.xlsx", sheetName="sheet1", col.names=TRUE, row.names=FALSE)
install.packages("foreign")
require(foreign)
install.packages("rjson")
require(rjson)
data$x3
View(data)
data[, c("Ce", "La")]
data$La
data[order(data$La), ]
data[order(data$La, decreasing=TRUE), ]
data[order(data$La, data$Lu), ]
data[data$La > 100, ]
data[data$La > 100 & data$x < 500, ]
na.omit(data)
data[!duplicated(data$La), ]
y <- table(data$La)
print(y)
names(y) [which(y==max(y))]
median(data$Ce)
mode(data$La)
res <- range(data$La)
diff(res)
quantile(data$La)
IQR(data$La, na.rm=TRUE)
N <- nrow(data)
var(data$La) * (N - 1) / N
var(data$Ce)
N <- nrow(data);
variance <- var(data$Eu) * (N - 1) / N;
sqrt(variance)
sd(data$Eu)
hist(data$La, breaks=10)
qqnorm(data$La)
qqline(data$La)
shapiro.test(data$La)
installed.packages("moments")
require(moments)
skewness(data$La)
kurtosis(data$La)
sum<-summary(data)
View(sum)
write.xlsx(data, file="data_summary.xlsx", sheetName="sheet1", col.names=TRUE, row.names=FALSE)
str(data)
barplot(data$La,xlab="La", ylab="concentration in ppm", main="Bar Chart 1", col="green", freq=FALSE)
barplot(data$La,xlab="La", ylab="concentration in ppm", main="Bar Chart 1", col="green", horiz=TRUE)
barplot(data$Ce, xlab="Ce", ylab="ppm", main="Ce Bar Chart", col=c("grey", "blue", "yellow"))
hist(data$Ce, main="histogram", xlab="Ce", col="green",border="blue", breaks=10)
plot(data$La, data$Ce, type="l", xlab="La", ylab="Ce", main="La-Ce correlations", col="blue")
plot(data$La, data$Ce, type="p", xlab="La", ylab="Ce", main="La-Ce correlations", col="blue")
pie(data$Lu, labels, main="Pie Chart")
install.packages("plotrix")
require(plotrix)
pie3D(data$La)
pie3D(data$La, labels=labels, explode=0.1, main="Pie Chart")
plot(data$La, data$Ce, xlab="La", ylab="Ce", main="scatterplot")
boxplot(data$La, main="boxplot", notch=FALSE, varwidth=TRUE,col=c("green", "purple", "blue"))
boxplot(data$La, main="boxplot", notch=TRUE, varwidth=TRUE,col=c("green", "purple", "blue"))
pairs(data$La)
install.packages("igraph")
require(igraph)
g <- graph(edges=c("John", "James", "James", "Mary", "Mary", "John"), directed=FALSE)
plot(g)
g <- graph(edges=c("John", "James", "James", "Mary", "Mary","John"), directed=TRUE);
plot(g)
require(ggplot2)
install.packages("stringr")
install.packages ("stringi")
install.package("colorspaces")
install.packages("labelling")
install.packages("munsell")
library(ggplot2)
set.seed(12)
var1 <- rnorm(100, mean=1, sd=1)
var2 <- rnorm(100, mean=2, sd=1)
var3 <- rnorm(100, mean=1, sd=2)
data <- data.frame(var1, var2, var3)
ggplot(data)
ggplot(data, aes(x=var1, y=var2))
ggplot(data, aes(x=var1, y=var2)) + geom_point(aes(color="red"))
ggplot(data, aes(x=var1, y=var2)) + geom_point(aes(color="red")) + geom_smooth()
ggplot(data, aes(x=var1, y=var2)) + geom_point (aes(color="red")) + geom_smooth() + labs(title="Scatter",x = "Xaxis", y = "Y-axis", color="Color")
ggplot(data, aes(x=var1, y=var2)) + geom_point(aes(color="red")) + geom_smooth() + labs(title="scatter",x="x-axis", y="y-axis") + theme_light()
ggplot(data, aes(x=var1, y=var2)) + geom_point(aes(color="red")) + geom_smooth() +  labs(title="scatter", x="x-axis", y="y-axis") + theme(plot.title=element_text(size=30, face="bold"), axis.text.x=element_text(size=15, face="bold"), axis.text.y=element_text(size=15, face="bold"))
d <- c(1, 5, 8, 9, 8, 2, 1)
df <- data.frame(d)
ggplot(df) + geom_bar(aes(color="grey", x=d)) +labs(title="bar chart") + theme_light()
ggplot(df) + geom_bar(aes(color="grey", x=d)) + coord_flip()+ labs(title="bar chart") + theme_light()
set.seed(12);
var1 <- rnorm(100, mean=1, sd=1)
var2 <- rnorm(100, mean=2, sd=1)
var3 <- rnorm(100, mean=1, sd=2)
data <- data.frame(var1, var2, var3)
ggplot(data, aes(x=var1)) + geom_histogram(bins=10,color="black", fill="grey") + labs(title="histogram")+theme_light()
ggplot(data, aes(x=var1)) + geom_density(fill="grey") +  labs(title="density")
ggplot(data) + geom_point(aes(color="red", x=var1, y=var2))+ geom_point(aes(color="green", x=var1, y=var3)) +  labs(title="scatter") + theme_light()
ggplot(data) + geom_line(aes(color="red", x=var1, y=var2))+ geom_line(aes(color="green", x=var1, y=var3)) +labs(title="scatter") + theme_light()
ggplot(data, aes(y=var2)) + geom_boxplot(fill="grey") +  labs(title="boxplot")
ggplot(data, aes(x=var1)) + geom_density(fill="grey") +  labs(title="density") + theme(panel.background=element_  rect(fill="yellow"), panel.grid.major=element_line(color="blue", size=2))
ggsave("D:/density.png")
install.packages("plotly")
require(plotly)
install.packages("ggplotly")
set.seed(12)
var1 <- rnorm(100, mean=1, sd=1)
var2 <- rnorm(100, mean=2, sd=1)
var3 <- rnorm(100, mean=1, sd=2)
data <- data.frame(var1, var2, var3)
gg <- ggplot(data) + geom_line(aes(x=var1, y=var2))
g <- ggplotly(gg)
g
Sys.setenv("plotly_username"="your plotly username")
Sys.setenv("plotly_api_key"="your api key")
api_create(g, filename="")
set.seed(123)
var1 <- rnorm(100, mean=2, sd=1)
var2 <- rnorm(100, mean=3, sd=1)
var3 <- rnorm(100, mean=3, sd=2)
data <- data.frame(var1, var2, var3)
data
apply(data, 1, mean)
apply(data,2,mean)
lapply(data$var1, mean)
sapply(data$var1, mean)
set.seed(123);
var1 <- rnorm(100, mean=2, sd=1);
var2 <- rnorm(100, mean=3, sd=1);
var3 <- rnorm(100, mean=3, sd=2);
data <- data.frame(var1, var2, var3);
sample(data$var1, 5, replace=TRUE)
data(iris)
summary(iris) 
iris_sample <- iris %>%  + group_by(Species) %>%  + sample_n(13)
iris_sample
# A tibble: 39 x 5
# Groups: Species
View(iris_sample)

View(iris_sample)
set.seed(123)
var1 <- rnorm(100, mean=2, sd=1)
var2 <- rnorm(100, mean=3, sd=1);
var3 <- rnorm(100, mean=3, sd=2);
data <- data.frame(var1, var2, var3)
cor(data$var1,  data$var2)
cov(data$var1,data$var2)
t.test(data$var1, mu=0.6)
t.test(data$var1, data$var2, var.equal=TRUE, paired=FALSE)
t.test(data$var1, data$var2, var.equal=FALSE, paired=FALSE)
t.test(data$var1, data$var2, paired=TRUE)
data <- c(B=200, c=300, D=400);
chisq.test(data)
var1 <- c("Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female")
var2 <- c("chocolate", "strawberry", "strawberry","strawberry", "chocolate", "chocolate", "chocolate","strawberry", "strawberry", "strawberry")
data <- data.frame(var1, var2)
data
data.table <- table(data$var1, data$var2)
data.table
chisq.test(data.table)
set.seed(123)
var1 <- rnorm(12, mean=2, sd=1)
var2 <- c("B", "B", "B", "B", "C", "C", "C", "C", "C", "D","D", "B")
data <- data.frame(var1, var2)
fit <- aov(data$var1 ~ data$var2, data=data)
fit
summary(fit)
set.seed(123)
var1 <- rnorm(12, mean=2, sd=1);
var2 <- c("B", "B", "B", "B", "C", "C", "C", "C", "C", "D",  "D", "B")
var3 <- c("D", "D", "D", "D", "E", "E", "E", "E", "E", "F", "F", "F")
data <- data.frame(var1, var2, var3)
fit <- aov(data$var1 ~ data$var2 + data$var3, data=data);
fit
summary(fit)
data(iris)
str(iris)
summary(iris)
res <- manova(cbind(iris$Sepal.Length, iris$Petal.Length) ~iris$Species, data=iris)
summary(res)
summary.aov(res)
